// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockfileutil

import mock "github.com/stretchr/testify/mock"

// FileHelper is an autogenerated mock type for the FileHelper type
type FileHelper struct {
	mock.Mock
}

// CreateDirIfNotExist provides a mock function with given fields: location
func (_m *FileHelper) CreateDirIfNotExist(location string) error {
	ret := _m.Called(location)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFileHelper interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileHelper creates a new instance of FileHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileHelper(t mockConstructorTestingTNewFileHelper) *FileHelper {
	mock := &FileHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
