// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockaws

import (
	cloudformation "github.com/aws/aws-sdk-go-v2/service/cloudformation"
	mock "github.com/stretchr/testify/mock"
)

// CfDescribeStacksPaginatorNewer is an autogenerated mock type for the CfDescribeStacksPaginatorNewer type
type CfDescribeStacksPaginatorNewer struct {
	mock.Mock
}

// Execute provides a mock function with given fields: client, params, optFns
func (_m *CfDescribeStacksPaginatorNewer) Execute(client cloudformation.DescribeStacksAPIClient, params *cloudformation.DescribeStacksInput, optFns ...func(*cloudformation.DescribeStacksPaginatorOptions)) *cloudformation.DescribeStacksPaginator {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, client, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudformation.DescribeStacksPaginator
	if rf, ok := ret.Get(0).(func(cloudformation.DescribeStacksAPIClient, *cloudformation.DescribeStacksInput, ...func(*cloudformation.DescribeStacksPaginatorOptions)) *cloudformation.DescribeStacksPaginator); ok {
		r0 = rf(client, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.DescribeStacksPaginator)
		}
	}

	return r0
}

type mockConstructorTestingTNewCfDescribeStacksPaginatorNewer interface {
	mock.TestingT
	Cleanup(func())
}

// NewCfDescribeStacksPaginatorNewer creates a new instance of CfDescribeStacksPaginatorNewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCfDescribeStacksPaginatorNewer(t mockConstructorTestingTNewCfDescribeStacksPaginatorNewer) *CfDescribeStacksPaginatorNewer {
	mock := &CfDescribeStacksPaginatorNewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
